### ISSUE TITLE
msisync_to_archive removal from contrib

### ISSUE THREAD

**Issue by cookie33** [irods/contrib#12]
Hi,

The function msisync_to_archive is now part of iRODS 4.1.8. Will it be removed from the contrib once iRODS 4.1.8 is released? Otherwise we will have a conflict if we install both 4.1.8 and the contrib package. Which one will it use than?

Greetings,

Robert

**Comment by trel** [comment]
The contrib is a collection of different packages, not a single monolithic set of things.  If you don't need the `msisync_to_archive` package specifically, then you don't need to install it.

We may remove it eventually, but for now, some on pre-4.1.8 may still find it helpful.
